database:
  host: localhost   # Default: localhost
  port: 3306        # Default: 3306
  user: root        # Default: root
  password:         # Default: <blank>
  name: refraction  # Default: refraction
